#!/usr/bin/env bash

# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

# This script is very similar to the pre-commit hook, except it
# unconditionally checks all files, which we have time for in CI.

exit_() {
    echo ""
    echo "$1"
    echo ""
    exit 1
}

## Check whether C/C++ source code has been formatted:
if ! ./scripts/format-c-code --quiet --whatif; then
    echo "C/C++ code not formatted correctly, IGNORING FOR NOW!"
    #exit_ "CI failed: please run ./scripts/format-c-code"
fi

## Check whether Python source code has been formatted:
if ! ./scripts/format-py-code --whatif; then
    exit_ "CI failed: please run ./scripts/format-py-code"
fi

# Check whether all scripts pass ShellCheck:
if ! ./scripts/check-linters; then
    exit_ "CI failed: please run ./scripts/check-linters"
fi
