#!/bin/bash

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

ENCLAVE_HEAP_SIZE=209715200
ENCLAVE_DEBUG_KEY=${BASE_DIR}/build/config/enclave_debug.key

SGX_LKL_RUN_EXEC=${BASE_DIR}/build/sgx-lkl-run
SGX_LKL_OPTIONS="\
  SGXLKL_TAP=sgxlkl_tap0 \
  SGXLKL_STHREADS=4 \
  SGXLKL_ETHREADS=4 \
  SGXLKL_HEAP=${ENCLAVE_HEAP_SIZE} \
  SGXLKL_KEY=${ENCLAVE_DEBUG_KEY} \
  SGXLKL_VERBOSE=1 \
  SGXLKL_TRACE_SYSCALL=0 \
  SGXLKL_TRACE_MMAP=0"

JRE_LIB_PATH="/opt/j2re-image/lib/amd64:/opt/j2re-image/lib/amd64/jli:/opt/j2re-image/lib/amd64/server"
DEFAULT_JRE_ARGS="\
  -Xms2000k \
  -XX:InitialCodeCacheSize=2000k \
  -XX:ReservedCodeCacheSize=2000K \
  -XX:CompressedClassSpaceSize=2000K \
  -XX:+UseCompressedClassPointers \
  -cp /app"

DISK_IMAGE=$1
ARGS="${@:2}"

env LD_LIBRARY_PATH=${JRE_LIB_PATH} ${SGX_LKL_OPTIONS} ${SGX_LKL_RUN_EXEC}  ${DISK_IMAGE} /opt/j2re-image/bin/java ${DEFAULT_JRE_ARGS} ${ARGS}

