#!/bin/bash

# shellcheck disable=SC2086,SC2124

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

EXECUTION_MODE=$1

if [ -f ${THIS_DIR}/../build/sgx-lkl-run-oe ]; then
    SGX_LKL_RUN_EXEC=${THIS_DIR}/../build/sgx-lkl-run-oe
else
    SGX_LKL_RUN_EXEC=$THIS_DIR/sgx-lkl-run-oe
fi

SGX_LKL_OPTIONS="\
  SGXLKL_MMAP_FILES=${SGXLKL_MMAP_FILES:-Shared}"

JRE_LIB_PATH="/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64:/usr/lib/jvm/java-1.8-openjdk/lib/amd64/jli"
DEFAULT_JRE_ARGS="\
  -Xms2000k \
  -XX:InitialCodeCacheSize=2000k \
  -XX:ReservedCodeCacheSize=4000K \
  -XX:CompressedClassSpaceSize=4000K \
  -XX:+UseCompressedClassPointers \
  -XX:+PerfDisableSharedMem \
  -XX:+UseMembar \
  -Dsun.zip.disableMemoryMapping=true \
  -cp /app"

DISK_IMAGE=$2

# if --debug option provided after execution_mode and disk_image as third option
# run sgx-lkl-java with sgx-lkl-gdb for debugging
#
# sample usage:
# sgx-lkl-java --hw-debug sgxlkl-java.img --debug

if [ "$3" == "--debug" ]; then
    if [ -f ${THIS_DIR}/../tools/gdb/sgx-lkl-gdb ]; then
        SGX_LKL_GDB=${THIS_DIR}/../tools/gdb/sgx-lkl-gdb
    else
        SGX_LKL_GDB=$THIS_DIR/sgx-lkl-gdb
    fi

    ARGS="${@:4}"
    env LD_LIBRARY_PATH=${JRE_LIB_PATH} ${SGX_LKL_OPTIONS} ${SGX_LKL_GDB} --args ${SGX_LKL_RUN_EXEC} ${EXECUTION_MODE} ${DISK_IMAGE} /usr/bin/java ${DEFAULT_JRE_ARGS} ${ARGS}
else
    ARGS="${@:3}"
    env LD_LIBRARY_PATH=${JRE_LIB_PATH} ${SGX_LKL_OPTIONS} ${SGX_LKL_RUN_EXEC} ${EXECUTION_MODE} ${DISK_IMAGE} /usr/bin/java ${DEFAULT_JRE_ARGS} ${ARGS}
fi
