#!/usr/bin/env bash

set -e

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

py_name="sgx-lkl-cfg.py"

if [ -f "$this_dir/$py_name" ]; then
    py_dir=$this_dir
else
    py_dir=$this_dir/../lib
fi

python3 "$py_dir/$py_name" "$@"
