trigger: none
pr: none

extends:
  template: template.yml
  parameters:
    publish: true
    nightly_build: false
    apt_repo_blob_container: apt
    test_timeout_minutes: 120 # ethread==1 takes longer to run
    ethreads:
    - 1
    - 4
    - 8
