trigger: none
pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
  paths:
    exclude:
    - '*.md'
    - 'docs/'

extends:
  template: template.yml
  parameters:
    publish: false
  env:
    MAA_CLIENT_ID: $(maaClientId)
    MAA_SECRET_KEY: $(maaSecretKey)
    MAA_APP_ID: $(maaAppId)
