/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.6
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "sgx-lkl-sign"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "sgx-lkl-sign"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1.0"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * file_arg;	/**< @brief Path to libsgxlkl.so that should get signed..  */
  char * file_orig;	/**< @brief Path to libsgxlkl.so that should get signed. original value given at command line.  */
  const char *file_help; /**< @brief Path to libsgxlkl.so that should get signed. help description.  */
  char * key_arg;	/**< @brief Path to enclave key file..  */
  char * key_orig;	/**< @brief Path to enclave key file. original value given at command line.  */
  const char *key_help; /**< @brief Path to enclave key file. help description.  */
  long stacksize_arg;	/**< @brief Size of the stack in bytes. Will be rounded up to align   with the size of a page. (default='32768').  */
  char * stacksize_orig;	/**< @brief Size of the stack in bytes. Will be rounded up to align   with the size of a page. original value given at command line.  */
  const char *stacksize_help; /**< @brief Size of the stack in bytes. Will be rounded up to align   with the size of a page. help description.  */
  long heapsize_arg;	/**< @brief Size of the heap in bytes. If set to zero the heap will   occupy the remaining space of the EPC. Setting this value to a value larger   than the EPC is allowed but might result in EPC paging. (default='0').  */
  char * heapsize_orig;	/**< @brief Size of the heap in bytes. If set to zero the heap will   occupy the remaining space of the EPC. Setting this value to a value larger   than the EPC is allowed but might result in EPC paging. original value given at command line.  */
  const char *heapsize_help; /**< @brief Size of the heap in bytes. If set to zero the heap will   occupy the remaining space of the EPC. Setting this value to a value larger   than the EPC is allowed but might result in EPC paging. help description.  */
  long threads_arg;	/**< @brief Maximum number of enclave threads. This determines the number   of TCS. This does not restrict the number of user-level threads used by an   application. (default='8').  */
  char * threads_orig;	/**< @brief Maximum number of enclave threads. This determines the number   of TCS. This does not restrict the number of user-level threads used by an   application. original value given at command line.  */
  const char *threads_help; /**< @brief Maximum number of enclave threads. This determines the number   of TCS. This does not restrict the number of user-level threads used by an   application. help description.  */
  int support_non_pie_arg;	/**< @brief Specify this if sgx-lkl-run needs to run with   SGXLKL_NON_PIE=1. (default='0').  */
  char * support_non_pie_orig;	/**< @brief Specify this if sgx-lkl-run needs to run with   SGXLKL_NON_PIE=1. original value given at command line.  */
  const char *support_non_pie_help; /**< @brief Specify this if sgx-lkl-run needs to run with   SGXLKL_NON_PIE=1. help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int file_given ;	/**< @brief Whether file was given.  */
  unsigned int key_given ;	/**< @brief Whether key was given.  */
  unsigned int stacksize_given ;	/**< @brief Whether stacksize was given.  */
  unsigned int heapsize_given ;	/**< @brief Whether heapsize was given.  */
  unsigned int threads_given ;	/**< @brief Whether threads was given.  */
  unsigned int support_non_pie_given ;	/**< @brief Whether support-non-pie was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
